### PR TITLE
(#638) Allow discovery with choria::service

### PR DESCRIPTION
**Pull request by smortex**
MCollective is being replaced with Choria.  The mcollective::service
class was used to know if a node was configured with MCollective or not.

Now that the service is being removed from the MCollective class, we
need to check for the equivalent class in the choria module,
choria::service.

For now, look for any of those two classes, so that legacy nodes not
using Choria can continue to behave as previously.

### CODE REVIEW

**Comment by ripienaar** [comment]
some basic test updates required here

**Comment by smortex** [comment]
Ooops!  Still failing…

```
        Validity
            Not Before: Nov 22 02:44:00 2019 GMT
            Not After : Nov 21 02:44:00 2020 GMT
```

meh…

**Comment by ripienaar** [comment]
Lovely, go ones also expired on the weekend, let me check tomorrow how to fix that..

**Comment by smortex** [comment]
I am working on adding a rake task to build new certificates chain ATM ;-)

**Comment by ripienaar** [comment]
Not checked exactly but its probably these https://github.com/choria-io/mcollective-choria/tree/master/spec/fixtures/intermediate and there's a Makefile, same ones are in go-choria

**Pull request merged**
